version: "3.9"
services:
  nacos:
    image: nacos/nacos-server:v2.0.4-slim
    container_name: nacos
    env_file:
      - ./env/nacos.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - "./conf/nacos.properties:/home/nacos/conf/application.properties"
    depends_on:
      - mysql-nacos
    restart: always
  mysql-nacos:
    image: mysql:8.0.16
    container_name: mysql-nacos
    env_file:
       - ./env/mysql-nacos.env
    volumes:
       - "./data/mysql-nacos:/var/lib/mysql"
       - "./init/nacos:/docker-entrypoint-initdb.d"
networks:
  default:
    external:
      name: cheese-net
