version: "3.9"
services:
  redis:
    image: redis:6.2
    container_name: cheese-redis
    ports:
      - "6379:6379"
    volumes:
      - "./conf/redis.conf:/usr/local/etc/redis/redis.conf"
  es:
    image: elasticsearch:7.12.1
    container_name: cheese-es
    env_file:
      - ./env/elasticsearch.env
    ports:
      - "9200:9200"
      - "9300:9300"
  mysql-biz:
    image: mysql:8.0.16
    container_name: cheese-mysql-biz
    env_file:
      - ./env/mysql-biz.env
    ports:
      - "3306:3306"
networks:
  cheese-net:
    external: true