version: "3.9"
services:
  frontend:
    image: cheeseocean/frontend:latest
    container_name: frontend
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/cond.d
