version: "3.9"
services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis:/data"
  es:
    image: elasticsearch:7.12.1
    container_name: es
    env_file:
      - ./env/elasticsearch.env
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./data/es:/usr/share/elasticsearch/data"
  mongo:
    image: mongo:5
    container_name: mongo
    env_file:
      - ./env/mongo.env
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/data/db"
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql-cheeseocean:/var/lib/mysql"
      - "./init/cheeseocean:/docker-entrypoint-initdb.d"
networks:
  default:
    external:
      name: cheese-net
